### ISSUE TITLE
The application crashes when I try to open the application

### ISSUE THREAD

**Issue by friendsmobile** [retrodaredevil/track-shooter#2]
# Project Information

* Repository: https://github.com/retrodaredevil/track-shooter
* Project Name:  track-shooter
* My Github Account: https://github.com/friendsmobile

# Expected behavior

When I try to open the application, all the options in the app should be displayed and the application should not be crash.

# Actual behavior

When I try to open the application, the application is crashes and applications are not open.

# How to reproduce

* [Download ](https://play.google.com/store/apps/details?id=me.retrodaredevil.game.trackshooter)the app 
* Try to open the application
* Note the Error

* Browser/App version:  Current Version 1.10
* Operating system: 6.0

# Recording Of The Bug

![20190608_162600](https://user-images.githubusercontent.com/51118734/59146706-4fecb480-89a6-11e9-8518-06e9172efc87.gif)

# Logcat

<pre><code>E/AndroidRuntime(30706): FATAL EXCEPTION: main

E/AndroidRuntime(30706): Process: me.retrodaredevil.game.trackshooter, PID: 30706

E/AndroidRuntime(30706): java.lang.ExceptionInInitializerError

E/AndroidRuntime(30706): 	at java.lang.reflect.Constructor.newInstance(Native Method)

E/AndroidRuntime(30706): 	at java.lang.Class.newInstance(Class.java:1690)

E/AndroidRuntime(30706): 	at android.app.Instrumentation.newActivity(Instrumentation.java:1078)

E/AndroidRuntime(30706): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2541)

E/AndroidRuntime(30706): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2769)

E/AndroidRuntime(30706): 	at android.app.ActivityThread.access$900(ActivityThread.java:177)

E/AndroidRuntime(30706): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1430)

E/AndroidRuntime(30706): 	at android.os.Handler.dispatchMessage(Handler.java:102)

E/AndroidRuntime(30706): 	at android.os.Looper.loop(Looper.java:135)

E/AndroidRuntime(30706): 	at android.app.ActivityThread.main(ActivityThread.java:5910)

E/AndroidRuntime(30706): 	at java.lang.reflect.Method.invoke(Native Method)

E/AndroidRuntime(30706): 	at java.lang.reflect.Method.invoke(Method.java:372)

E/AndroidRuntime(30706): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1405)

E/AndroidRuntime(30706): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1200)

E/AndroidRuntime(30706): Caused by: com.badlogic.gdx.utils.GdxRuntimeException: Couldn't load shared library 'gdx' for target: Linux, 32-bit

E/AndroidRuntime(30706): 	at com.badlogic.gdx.utils.SharedLibraryLoader.load(SharedLibraryLoader.java:125)

E/AndroidRuntime(30706): 	at com.badlogic.gdx.utils.GdxNativesLoader.load(GdxNativesLoader.java:33)

E/AndroidRuntime(30706): 	at com.badlogic.gdx.backends.android.AndroidApplication.<clinit>(AndroidApplication.java:60)

E/AndroidRuntime(30706): 	... 14 more

E/AndroidRuntime(30706): Caused by: java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/me.retrodaredevil.game.trackshooter-1/base.apk"],nativeLibraryDirectories=[/vendor/lib, /system/lib]]] couldn't find "libgdx.so"

E/AndroidRuntime(30706): 	at java.lang.Runtime.loadLibrary(Runtime.java:366)

E/AndroidRuntime(30706): 	at java.lang.System.loadLibrary(System.java:988)

E/AndroidRuntime(30706): 	at com.badlogic.gdx.utils.SharedLibraryLoader.load(SharedLibraryLoader.java:119)

E/AndroidRuntime(30706): 	... 16 more
</code></pre>

**Comment by retrodaredevil** [comment]
Thanks for reporting this. This error is a weird one. What device are you using? Before the 1.10 update, did you have this app working at all? Have you ever been able to launch it?

The only two android devices I can test on right now have android version 9 and android version 4, so it will probably be difficult for me to solve this issue. If I do try to fix it, I'll be trying to fix it blindly. I might try the solution here in the next update. https://stackoverflow.com/questions/46840146/use-objectbox-with-libgdx

**Comment by friendsmobile** [comment]
welcome sir 

i am using samsung j7 2016 and android version is 6.0

**Comment by retrodaredevil** [comment]
Just making this comment for me to look at later.

It looks like someone had a problem with libGDX and ram usage, so this probably isn't the problem, but it does mention J7: https://gamedev.stackexchange.com/questions/132307/libgdx-game-crashes-on-some-devices-without-any-errors-logs/132408
The problem could be that I don't have libgdx.so in the correct folder for the J7 and I need mips and mips64: https://stackoverflow.com/questions/30782848/how-to-use-32-bit-native-libraries-on-64-bit-android-device (not likely)

I might see if anyone I know has a J7 and see if they can reproduce this error since I can't do it.

**Comment by friendsmobile** [comment]
sir, I have 0 % programming knowledge.

Thank you very much now the bug has been fixed

![20190609_141526](https://user-images.githubusercontent.com/51118734/59157266-969ce600-8a5c-11e9-9fef-2f67270b2c31.gif)

**Comment by retrodaredevil** [comment]
That's really weird. If that happens again, let me know. Sometimes if an app crashes android will give you the option to report it. I'm not sure why your phone didn't give you the option when it crashed.

Thanks for reporting this and I hope you have fun playing the game!
